### ISSUE TITLE
compute shader, number of groups?

### ISSUE THREAD

**Issue by raptoravis** [polymonster/pmtech#37]
the 1st param of renderer_dispatch_compute should be number of groups, right?

![image](https://user-images.githubusercontent.com/4395022/64475787-c2457e80-d1b9-11e9-8af3-ca368bec2288.png)

**Comment by polymonster** [comment]
Yes the grid is number of pixel processed per group / thread in each axis., I think maybe it is a bit confusing because d3d does not use num_threads in d3d they are specified inside the pmfx shader but in metal you pass the number of threads and the grid into the graphics api.

I am just working on Vulkan api now and will be looking more into improving the compute API so I think a design would be nice to be able to get the number of groups from the pmfx shader which we already can specify, but having the c++ api to obtain that info would be nicer to make HLSL, Metal and Vulkan SPIRV feel the same would be nice.

**Comment by raptoravis** [comment]
It seems good to specify the grid number by pen::renderer_dispatch_compute, but internally, pen::renderer_dispatch_compute can do a transform to group number.

btw, I quite like the way of pmtech is working and thanks for the sharing.

but I don't quite understand to bother to record the render_cmd to _cmd_buffer. why not to use the dx11's deferred context?

**Comment by polymonster** [comment]
I see, yes we could make the transform happen inside the dispatch function.. I will take a look at this once I get the Vulkan compute implementation working just to see how all the platforms work differently and make the api as consistent as possible.

The reason for the Cmd buffer is historical and it is to allow OpenGL to be multi threaded as well.. originally I had a d3d9 rendering backend and back in the day when I was working on Xbox 360 games the command buffer was an optimisation I made to push the d3d driver overhead on to a separate core because there was not a deferred context at that time.

I am actually designing a new engine / renderer for my job and it does not use a command buffer but instead using multi threaded rendering contexts and makes monolithic pipelines like Vulkan instead of setting separate render states.

Thanks for using pmtech, I hope it helps you to make some cool stuff.. I am still actively working on it and although some of the tenderer design might be a bit dated now I plan on sticking with it and maintaining the project so if you do have issues I am happy to help out and improve things :)

**Comment by raptoravis** [comment]
thanks
