### ISSUE TITLE
the hot reload seems broken

### ISSUE THREAD

**Issue by raptoravis** [polymonster/pmtech#38]
Hi,

I tried the example of 'blend_modes'. it worked well.

however, when I tried the hot reloading, it crashed with the following:
1. open blend_modes.jsn and add `technique          : debug` in `view_no_blend`, the reload was triggered but with a crash.

![image](https://user-images.githubusercontent.com/4395022/64486367-ce374c00-d25e-11e9-9d97-b8f17d8dd27a.png)

**Comment by polymonster** [comment]
I am aware of this crash and it has been on my list for a while.. it doesn’t happen on Mac and I am mainly working on Mac/metal so it hasn’t been too much of an issue for me.. I will prioritise this for you and try and get you a fix this week.

**Comment by raptoravis** [comment]
![image](https://user-images.githubusercontent.com/4395022/64496818-81458b00-d2db-11e9-9046-4f033169cbc5.png)

I guess `renderer_dispatch` is intended to consume commands using the od resources. but, I am suspecting it can't as `renderer_dispatch` should be invoked in the main thread?

**Comment by polymonster** [comment]
I have fixed this now for the blend modes sample at least.

The issue was in blend_modes.cpp where I was taking a static u32 to a blend mode handle, these need to be obtained every frame because the handle changes if we delete and reload the pmfx config.

There might be some other samples and code which takes copies of handles and then they might become dangling, I need to do some more tests and investigation.

renderer_dispatch should not be called.. this is a mistake. it should be renderer_consume_cmd_buffer which will wait on vsync and prevent us using gpu resources that might be in flight on the gpu.

**Comment by raptoravis** [comment]
wow, it works like a charm! thanks

**Comment by raptoravis** [comment]
sorry that after getting the latest and tried `rasterizer_state`, it crashed but I could not figure out it:

![image](https://user-images.githubusercontent.com/4395022/64662371-c653f380-d47a-11e9-8654-0b321e2c11ad.png)

**Comment by polymonster** [comment]
Another fix is in now, 

In this case the blend state which was being released has failed to create, this was because the render target write mask was set to 0xff and 0xf is the max accepted value.

I have also added some code to guard against shared render states being deleted twice.

There is a bigger issue to tackle here though, if something takes a render state handle (u32) from pmfx and then stores it for re-use.. a  hot reload may make it become stale and can cause issues.

I think a longer term solution is to make get_render_state return a reference type which can be updated but it is quite a large change.

The short term solution is to make sure to not keep hold of pmfx render handles and instead get the by hash every frame if you need to.

Hopefully this should improve the hot reload, let me know if you encounter any more issues! :)

**Comment by raptoravis** [comment]
so cool, it works! thank!
