### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by Dmunch04** [polymonster/pmtech#48]
are there any docs? and if not are there any plans to make them?

**Comment by polymonster** [comment]
I have not got a huge amount of documentation just because it’s been constantly iterated on and changing over time.

There are a few things on the wiki, how to build and some high level overviews.

If you want documentation on anything particular feel free to ask and I can think about adding whatever, but the code should be fairly easy to follow from looking at the header files and using the examples as a starting point.

**Comment by Dmunch04** [comment]
okay. i was hoping there would be docs for the code. but thats fine. thanks for the reply
